apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customers-service
  name: customers-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.customersservice.replicaCount }}
  selector:
    matchLabels:
      app: customers-service
  strategy: {}
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      serviceAccountName: rds-access-sa
      containers:
      - image: {{ .Values.customersservice.image }}:{{ .Values.customersservice.version }}
        name: customers-service
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value:  kubernetes,test
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.database.username }}
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: dbpassword
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://{{ .Values.database.host }}/{{ .Values.database.name }}?user={{ .Values.database.name }}&password={{ .Values.database.password }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      restartPolicy: Always